global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: [node_exporter:9100]
  - job_name: nestjs-app
    metrics_path: '/api/api/metrics'
    static_configs:
      - targets: [45.156.22.249]
      
