global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: [node_exporter:9100]
  - job_name: nestjst-app
    static_configs:
      - targets: [45.156.22.249:8000]
      
