name: Continuous deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Test SSH connection
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
            ssh -o StrictHostKeyChecking=no \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo 'Connection successful!'"

      - name: Deploy backend
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
              cd ${{ secrets.BACKEND_PATH }} && \
              git config pull.rebase true && \
              git pull && \
              docker compose down && \
              docker compose build --pull && \
              docker compose up -d"

      - name: Deploy frontend
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" \
            ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
              cd ${{ secrets.FRONTEND_PATH }} && \
              git pull && \
              export PATH=\$PATH:/root/.local/share/pnpm/ && \
              pnpm install && \
              pnpm build && \
              pm2 delete frontend 2> /dev/null || true && \
              pm2 start pnpm --name frontend -- start"